### ISSUE TITLE
Mac OS X en akatsak daude

### ISSUE THREAD

**Issue by galder542** [UPV-EHU-Bilbao/winterTwitter#16]
Datu basea ireki ematen diodanean Mac OS X en aplikazioa kolgatuta gelditzen da.

**Comment by Porobu** [comment]
Macek crossplatformlookandfeel behar du
GALDER CAMBIA EL MAC YA

**Comment by Porobu** [comment]
@juananpe OSXen lerro honek zer itzultzen du?
System.out.println(System.getProperty("os.name"));

**Comment by juananpe** [comment]
@Porobu "Mac OS X"
